version: '3'
services:
  ### Posgres database for Inventory
  db-inventory:
    container_name: db-user
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ### Posgres database for Products
  db-products:
    container_name: db-post
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: post_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432